# Generated by Django 5.2.8 on 2025-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='used_referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
